# Creating a *`DataFrame`*
* ### `DataFrame` is an another datatype in Pandas.
* ### `DataFrame` is basically a bunch of series placed together veritcally. |||

In [1]:
import numpy as np 
import pandas as pd

## Creating a `DataFrame`
### There are 2 ways to create a `Pandas` `DataFrame`:

### 1. Using `Dictionary` collection:

In [2]:
employees_dataset_dict = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
employees_df1 = pd.DataFrame(data = employees_dataset_dict)

employees_df1

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

### 2. Using 2D `List` collection:

In [3]:
columns: list[str] = ["Name", "Age", "City", "Salary"]

employees_dataset_list :list[list] = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]

employees_df2 = pd.DataFrame(data = employees_dataset_list, columns = columns)

employees_df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

#### `Indexing` & `Slicing` of `DataFrame`:

In [4]:
#Single column would be shown as a series:
employees_df2['Salary']

0    65000
1    70000
2    62000
3    85000
Name: Salary, dtype: int64

In [5]:
#Multiple columns would be shown as DataFrame:
employees_df2[["Name","City"]]

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

### Creating a new column:

In [6]:
employees_df2['Position'] = ["Doctor","Eng.","Doctor","Eng."]
employees_df2

    Name  Age      City  Salary Position
0   John   28  New York   65000   Doctor
1   Anna   34     Paris   70000     Eng.
2  Peter   29    Berlin   62000   Doctor
3  Linda   42    London   85000     Eng.

### Creating Rows:

In [7]:
new_df = pd.DataFrame(data = {
                       'Name': ['Lester'],
                       'Age' : [45],
                       'City': ['Beverly Hills'], 
                       'Salary': [65000],
                       'Position': ['Film Director']})

pd.concat((employees_df2, new_df), ignore_index = True)

     Name  Age           City  Salary       Position
0    John   28       New York   65000         Doctor
1    Anna   34          Paris   70000           Eng.
2   Peter   29         Berlin   62000         Doctor
3   Linda   42         London   85000           Eng.
4  Lester   45  Beverly Hills   65000  Film Director

### `Removing` Columns:

In [8]:
df = employees_df2.copy()

In [9]:
df.drop(labels = ['City'], axis = 1, inplace = False)

    Name  Age  Salary Position
0   John   28   65000   Doctor
1   Anna   34   70000     Eng.
2  Peter   29   62000   Doctor
3  Linda   42   85000     Eng.

In [10]:
"""
    If the inplace = False then the drop will not affect the DataFrame and will just return a view
"""
df.drop(columns=['City'], inplace = False)

    Name  Age  Salary Position
0   John   28   65000   Doctor
1   Anna   34   70000     Eng.
2  Peter   29   62000   Doctor
3  Linda   42   85000     Eng.

In [11]:
#City is not dropped in the orignal DataFrame
df

    Name  Age      City  Salary Position
0   John   28  New York   65000   Doctor
1   Anna   34     Paris   70000     Eng.
2  Peter   29    Berlin   62000   Doctor
3  Linda   42    London   85000     Eng.

In [12]:
df.drop(columns = ['City'], inplace = True)
df

    Name  Age  Salary Position
0   John   28   65000   Doctor
1   Anna   34   70000     Eng.
2  Peter   29   62000   Doctor
3  Linda   42   85000     Eng.

### `Removing` Rows:

In [13]:
df2 = employees_df2.copy()

In [14]:
df2.drop(labels = 0, axis = 0, inplace = False)

    Name  Age    City  Salary Position
1   Anna   34   Paris   70000     Eng.
2  Peter   29  Berlin   62000   Doctor
3  Linda   42  London   85000     Eng.

In [15]:
df2.drop(index = 0, axis = 0, inplace = False)

    Name  Age    City  Salary Position
1   Anna   34   Paris   70000     Eng.
2  Peter   29  Berlin   62000   Doctor
3  Linda   42  London   85000     Eng.

### Selecting `Rows`

In [16]:
#locate 0th and 1st row
df.loc[[0, 1]]

   Name  Age  Salary Position
0  John   28   65000   Doctor
1  Anna   34   70000     Eng.

In [ ]:
#locate row based based on its index
employees_df1.iloc[3]

Name       Linda
Age           42
City      London
Salary     85000
Name: 3, dtype: object

### Selection of a `certain part` of `DataFrame`, `Slicing`:

In [19]:
#df.loc[[Rows]][["Columns"]]
employees_df1.loc[[0,1]][["City","Salary"]]

       City  Salary
0  New York   65000
1     Paris   70000

In [ ]:
#Numpy based selection:

#1. Select from 0 to 2 rows and all columns
employees_df1.iloc[: 2, :]

   Name  Age      City  Salary
0  John   28  New York   65000
1  Anna   34     Paris   70000

In [ ]:
#df.iloc[[Rows]][["Columns"]]
# ~> iloc returns a series or a dataframe whose rows are sliced and then when can slice the columns
# ~> iloc is faster than loc as iloc does slicing based on index rather than name

employees_df1.iloc[[0,1]][["Age","Salary"]]

   Age  Salary
0   28   65000
1   34   70000

In [ ]:
#2 Select 1st row and the 3rd till the last column 
employees_df1.iloc[:1, 2 : ]

       City  Salary
0  New York   65000

### Conditional Selection | `Boolean Masking`
* Boolean masking is a vectorized operation similar to map function.
* The operation/comparision is applied to every row in the DataFame/Series efficiently
* It returns a boolean Series of True or False.
* This boolean series is applied to a DataFrame or Series.

In [ ]:
# A filter to remove every employee whose age is above 30


age_mask = employees_df2["Age"] > 30
age_mask

0    False
1     True
2    False
3     True
Name: Age, dtype: bool

In [ ]:
employees_df2[age_mask]

    Name  Age    City  Salary Position
1   Anna   34   Paris   70000     Eng.
3  Linda   42  London   85000     Eng.

#### Filter those people whose age is above 30 and their city must be paris

In [ ]:
#Always provide the condition in closed round brackets
mask2 = (df2['Age'] > 30) & (df2['City'] == "Paris")

#OR

mask2 = age_mask & (df2['City'] == "Paris")

df2[mask2]

   Name  Age   City  Salary Position
1  Anna   34  Paris   70000     Eng.

### Condition-based filtering by `.loc[]`

In [23]:
df2.loc[mask2]

#Only show certain columns
df2.loc[mask2, ['Name', 'Age', 'Salary']]

   Name  Age  Salary
1  Anna   34   70000

#### Why Pandas use bit-wise operators i.e. `&`, `|`, `!`, `~` etc... instead of logical operators like `and`, `or`, `not` etc...
* Reason is, logical operatiors perform atomic operations i.e. either condition is true or something is false. Ambiguity is not allowed.
* But in a DataFrame similar to above one. We want to filter the DataFrame frame by `age > 30` and `City == 'Paris`. If `(employees_df1['Age'] > 30)` and `(employees_df1['City'] == "Paris")` is performed. 
The bool result would be:
[[False],
 [True],
 [False],
 [False]]
* Here, Assuming the list is a DataFrame. There are two boolean values at the same time. That's why the value is ambiguious.
* Similar thing happens with NumPy arrays:
    `x = np.array([2,4,6])`
    `x%2 == 0` and `x != 3`

    `ValueError`: The truth value of an array with more…
* And these logical operator are not modifiable but bit-wise are... `&`, `|`, `!`, `~` are modifialble by operator overriding using dunder methods.