# `Pivot Tables` and `Crosstabs`:

In [1]:
import numpy as np 
import pandas as pd

In [2]:
data = {
    'Date': pd.date_range('2023-01-01', periods = 20),#This will increment the date.
    'Product': ['A', 'B', 'C', 'D'] * 5,#To repeat the values...
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West',
               'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}

df = pd.DataFrame(data)

df['Month'] = df['Date'].dt.month_name()
df['Quarter'] = 'Q' + df['Date'].dt.quarter.astype(str)
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    291     43   John  January      Q1
1  2023-01-02       B   West    429     96   Mary  January      Q1
2  2023-01-03       C  North    615     36    Bob  January      Q1
3  2023-01-04       D  South    288     24  Alice  January      Q1
4  2023-01-05       A   East    250     83   John  January      Q1
5  2023-01-06       B   West    832     39   Mary  January      Q1
6  2023-01-07       C  North    653     98    Bob  January      Q1
7  2023-01-08       D  South    991     82  Alice  January      Q1
8  2023-01-09       A   East    654     44   John  January      Q1
9  2023-01-10       B   West    427     59   Mary  January      Q1
10 2023-01-11       C  North    611     33    Bob  January      Q1
11 2023-01-12       D  South    990     52  Alice  January      Q1
12 2023-01-13       A   East    512     81   John  January      Q1
13 2023-01-14       B   West    135     43   Mary  January      Q1
14 2023-01-15       C  North    660     60    Bob  January      Q1
15 2023-01-16       D  South    429     71  Alice  January      Q1
16 2023-01-17       A   East    563     60   John  January      Q1
17 2023-01-18       B   West    780     80   Mary  January      Q1
18 2023-01-19       C  North    649     84    Bob  January      Q1
19 2023-01-20       D  South    261     33  Alice  January      Q1

## Creating a `Pivot Table`:

In [8]:
pd.pivot_table(data = df, index = 'Region', columns = 'Product', values = 'Sales', aggfunc = 'count')

Product    A    B    C    D
Region
East     5.0  NaN  NaN  NaN
North    NaN  NaN  5.0  NaN
South    NaN  NaN  NaN  5.0
West     NaN  5.0  NaN  NaN

In [9]:
pd.pivot_table(data = df, index = 'Region', columns = 'Product', values = 'Sales', aggfunc = 'sum')

Product       A       B       C       D
Region
East     2270.0     NaN     NaN     NaN
North       NaN     NaN  3188.0     NaN
South       NaN     NaN     NaN  2959.0
West        NaN  2603.0     NaN     NaN

In [4]:
pivot2 = pd.pivot_table(data = df, index = 'Region', columns = 'Product', values = ['Sales', 'Units'], aggfunc = 'sum')
pivot2
# Example: How much is the 'sum' of 'Sales' The Region was 'East' and Product was 'A' i.e. 2133.0 ...
# Example: How much is the 'sum' of 'Units' The Region was 'East' and Product was 'A' i.e. 283.0 ...

          Sales                          Units
Product       A       B       C       D      A      B      C      D
Region
East     2270.0     NaN     NaN     NaN  311.0    NaN    NaN    NaN
North       NaN     NaN  3188.0     NaN    NaN    NaN  311.0    NaN
South       NaN     NaN     NaN  2959.0    NaN    NaN    NaN  262.0
West        NaN  2603.0     NaN     NaN    NaN  317.0    NaN    NaN

## Creating a `CrossTab`:

In [5]:
#Make a DataFrame where the pairs are repeated/frequency table of Product-Region pairs 
pd.crosstab(df['Region'], df['Product']) 
# Example: How many times The Region was 'East' and Product was 'A' i.e. 5 times

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0

In [6]:
pd.crosstab(df['Region'], df['Product'], values = df['Sales'], aggfunc ='sum')
# Example: How much is the 'sum' of 'Sales' The Region was 'East' and Product was 'A' i.e. 2759.0 ...

Product       A       B       C       D
Region
East     2270.0     NaN     NaN     NaN
North       NaN     NaN  3188.0     NaN
South       NaN     NaN     NaN  2959.0
West        NaN  2603.0     NaN     NaN

In [7]:
pd.crosstab(df['Sales'], df['Units'])
# Example: How many times The Sales was '158' and Units was '81' i.e. 5 times

Units  24  33  36  39  43  44  52  59  60  71  80  81  82  83  84  96  98
Sales
135     0   0   0   0   1   0   0   0   0   0   0   0   0   0   0   0   0
250     0   0   0   0   0   0   0   0   0   0   0   0   0   1   0   0   0
261     0   1   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
288     1   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
291     0   0   0   0   1   0   0   0   0   0   0   0   0   0   0   0   0
427     0   0   0   0   0   0   0   1   0   0   0   0   0   0   0   0   0
429     0   0   0   0   0   0   0   0   0   1   0   0   0   0   0   1   0
512     0   0   0   0   0   0   0   0   0   0   0   1   0   0   0   0   0
563     0   0   0   0   0   0   0   0   1   0   0   0   0   0   0   0   0
611     0   1   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
615     0   0   1   0   0   0   0   0   0   0   0   0   0   0   0   0   0
649     0   0   0   0   0   0   0   0   0   0   0   0   0   0   1   0   0
653     0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   1
654     0   0   0   0   0   1   0   0   0   0   0   0   0   0   0   0   0
660     0   0   0   0   0   0   0   0   1   0   0   0   0   0   0   0   0
780     0   0   0   0   0   0   0   0   0   0   1   0   0   0   0   0   0
832     0   0   0   1   0   0   0   0   0   0   0   0   0   0   0   0   0
990     0   0   0   0   0   0   1   0   0   0   0   0   0   0   0   0   0
991     0   0   0   0   0   0   0   0   0   0   0   0   1   0   0   0   0